version: "3"
services:
  ouronote-web:
    build: .
    working_dir: /usr/src/app
    # user: "node"
    # volumes:
    #   - ./:/usr/src/app
    ports:
      - 4430:4430
      - 8080:8765
    environment:
      - PORT=8081
      - HTTPS_PORT=4430
      - TZ=America/New York
    command: "npm start"
  # ouronote-gun:
  #   image: gundb/gun
  #   ports:
  #     - 8765:8765
