FROM mcr.microsoft.com/devcontainers/typescript-node:0-18
# RUN sudo apt-get update && apt-get #
# - [x] generate self-signed certs
# - [ ] initial build hash
# - [ ] ng completion
# - [ ] chromium for tests
